including element name in the output
muon-spectroscopy-computational-project/muon-galaxy-tools pull request #150
Opened 2024-06-06 11:43 UTC by subindev-d

Adding element as part of the output labels

2024-06-06 13:22 UTC, leandro-liborio approved these changes

2024-06-06 13:33 UTC, patrick-austin requested changes

2024-06-06 13:33 UTC, patrick-austin commented on mudirac/mudirac.xml
>          <collection name="states" format="tabular" label="States" type="list">
Is there a reason to not include the element in the label for this output? As it's present in all the others should we be consistent?

```suggestion
        <collection name="states" format="tabular" label="States (${element})" type="list">
```

2024-06-07 08:38 UTC, patrick-austin approved these changes

2024-06-07 08:40 UTC, merged